FROM python:3.12-slim

RUN useradd -m -u 1000 user

USER user

ENV PATH=$PATH:/home/user/.local/bin

WORKDIR /app

COPY --chown=user pyproject.toml uv.lock* /app/

RUN pip install --upgrade pip \
    && pip install uv gradio \
    && uv sync

COPY --chown=user . /app/

EXPOSE 7860
ENV GRADIO_SERVER_NAME="0.0.0.0"

CMD ["uv", "run", "gradio", "run", "gradio_app.py", "--server_port=7860", "--server_name=0.0.0.0"]