name: CI/CD Pipeline
permissions:
  contents: write

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}
  HF_USER: ${{secrets.HF_USER}}
  HF_API_TOKEN: ${{secrets.HF_API_TOKEN}}
  HF_SPACE_NAME: ${{secrets.HF_SPACE_NAME}}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync

    - name: Lint and format code with Ruff
      run: |
        uv run ruff format src/
        uv run ruff check src/ --fix

    - name: Gradio app health check
      run: |
        nohup uv run gradio_app.py &
        sleep 10
        curl --fail http://localhost:7860 || exit 1
      shell: bash

    - name: Cleanup Gradio process
      run: |
        pkill -f "uv"

  cd_pipeline:
    runs-on: ubuntu-latest
    needs: [ci_pipeline]

    steps:
    - uses: actions/checkout@v3

    - name: Docker login
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

    - name: Get current date
      run: echo "DATE=$(date +'%Y-%m-%d--%M-%S')" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ env.DATE }}

    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:${{ env.DATE }}

    - name: Update the HF Space
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        REPO_NAME: ${{secrets.REPO_NAME}}
        DATE: ${{ env.DATE }}
        HF_USER: ${{secrets.HF_USER}}
        HF_SPACE_NAME: ${{secrets.HF_SPACE_NAME}}
        HF_API_TOKEN: ${{secrets.HF_API_TOKEN}}
      run: |
        pip install huggingface_hub
        python scripts/push_gradio_hf_space.py